import React, { useState, useEffect } from 'react';
import './App.css';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import Home from 'C:\\Users\\ukmak\\Documents\\Share2Teach\\share2tech\\src\\pages\\index';
import MathPage from './pages/math';

const App: React.FC = () => {
  const [menuOpen, setMenuOpen] = useState<boolean>(false);
  const [hovering, setHovering] = useState<boolean>(false);

  const toggleMenu = (): void => {
    setMenuOpen(!menuOpen);
  };

  const handleMouseEnter = (): void => {
    setHovering(true);
  };

  const handleMouseLeave = (): void => {
    setHovering(false);
  };

  useEffect(() => {
    if (!hovering) {
      const timer = setTimeout(() => setMenuOpen(false), 1000);
      return () => clearTimeout(timer);
    }
  }, [hovering]);

  return (
    <Router>
      <div className="App">
        <header className="App-header">
          <div className="header-left">
            <button className="menu-button" onClick={toggleMenu}>
              Menu
            </button>
            {menuOpen && (
              <nav
                className="dropdown-menu"
                onMouseEnter={handleMouseEnter}
                onMouseLeave={handleMouseLeave}
              >
                <ul className="nav-links">
                  <li><Link to="/" onClick={() => setMenuOpen(false)}>Home</Link></li>
                  <li><Link to="/mathematics" onClick={() => setMenuOpen(false)}>Mathematics</Link></li>
                  {/* ... other list items ... */}
                </ul>
              </nav>
            )}
          </div>
          <h1 className="logo-title">Share2Teach</h1>
          <div className="header-right">
            <button className="login-button">Login</button>
          </div>
        </header>
        <main className="main-content">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/mathematics" element={<MathPage />} />
            {/* Add more routes for other subjects here */}
          </Routes>
          <footer className="footer">
            <div className="footer-content">
              <div className="disclaimer">
                <p><strong>Disclaimer:</strong></p>
                <p>
                  The resources available on this website are primarily the work of students. While we strive to maintain a high standard of quality, we cannot guarantee the accuracy, reliability, or completeness of the content provided. Users are encouraged to critically evaluate the materials and adopt them at their own discretion. Neither the founders nor North-West University assume responsibility for any errors, omissions, or for the results obtained from the use of this information. Design images are generated by ChatGPT (Open AI, 2023).
                </p>
              </div>
              <div className="reference">
                <p><strong>Reference:</strong></p>
                <p>
                  OpenAI. (2023). <em>ChatGPT (Mar 14 version)</em> [Large language model]. <a href="https://chat.openai.com/chat">https://chat.openai.com/chat</a>
                </p>
              </div>
            </div>
          </footer>
        </main>
      </div>
    </Router>
  );
}

export default App;