import React from 'react';
import './ContributorsPage.css';
import NWU_UNESCO from './Images/NWU&UNESCO.png';

function ContributorsPage() {
    return (
    <div className="contributors-page">
        <h1>Contributors</h1>
        <div className="contributors-content">
        <h2>FOUNDERS</h2>
        <p>DR CHANTELLE BOSCH<br/>PROF. DOROTHY LAUBSCHER</p>
        
        <h2>ADMINISTRATIVE ASSISTANCE</h2>
        <p>MATTHEW BODENSTEIN<br/>LARISSA VAN SITTERT<br/>OMPHEMETSE PHEELWANE<br/>MEGAN FOURIE</p>
        
        <h2>RESOURCE CONTRIBUTORS</h2>
        <p>
            ADAMS, EUGIE<br/>ANKHOMA, N<br/>AUSTIN, N<br/>BAAITJIES, LINCOLN<br/>BEKKER, RENÉ<br/>BHAMBATHA, M<br/>BRUNSDON, C<br/>BUTHELEZI, THANDA<br/>BUYS, MINE<br/>CAROLUS, AL<br/>CHAMBERS, TOMMY<br/>CHOBA, CONNIE<br/>COERECIUS, LIZE<br/>COETZEE, ELZETTE<br/>COETZEE, IZELLE<br/>COETZEE, SANDRI<br/>DAFFUE, MONIQUE<br/>DANIELS, LAKIN<br/>DE KOCK, MIANÉ<br/>DE LANGE, C<br/>DE SWARDT, SAMANTHA<br/>DE WET, LEANDRI<br/>DITHIPE, MT<br/>DLAMINI, MPHUMELELI<br/>DREW, DANIELLE<br/>DU BUISSON, C<br/>DU PLESSIS, D<br/>DU PLESSIS, ELMIEN<br/>DUNN, KEARA<br/>ELLIS, CHARL<br/>ENEVER, CHAN<br/>ENGELBRECHT, STEPHAN<br/>FAKU, THEBE<br/>FARMER, TONY<br/>FOURIE, A<br/>FOURIE, C<br/>FRANKEN, ANJÉ<br/>FRANSMAN, LANDY<br/>FRITZ, STEPHNIE<br/>GANYA, O<br/>GODANA, SV<br/>GOOSEN, CLAUD<br/>HELM, STEFNE<br/>HENDERSON, WANEASE<br/>HENDRIKS, TAMMY<br/>HLONGWANE, KG<br/>HOOPER, KAYLA<br/>HORN, MARNA<br/>HORN, ZURETHA<br/>HORNIET, SELDENE<br/>JACOBS, KIKI<br/>JANSE VAN RENSBURG, S<br/>JASONI, GG<br/>JOHNSTON, GENE<br/>JOOSTE, AJ<br/>KAKORA, JADE<br/>KATE, PALESA<br/>KELLY, KEANAN<br/>KEYSER, JO-DENE<br/>KHUMALO, KHUMALO KEKETSO<br/>KHUNE, MVK<br/>KOEN, ELRI<br/>KOLASE, BULI<br/>KOLOBE, EGNAR<br/>KROEZE, JANDRI<br/>LE ROUX, JUANE<br/>LEE, BERNADEEN<br/>LEGOTLO, OMPONE<br/>LETHOBA, RELEBOGILE<br/>LETLHOMO, EL<br/>LOMBARD, CHANE<br/>MAGA, NTHABISENG<br/>MAJATLADI, BONOLO<br/>MALAN, JANA<br/>MARITZ, NA<br/>MARUPING, MAIRESHA<br/>MASINGA, ZANI<br/>MATROSE, SIYABONGA<br/>MATSHA, MC<br/>MATTHYS, TRISTAN<br/>MAUTLWA, TT<br/>MBALANE, KHENSO<br/>MBELEKWANE, BRADLEY<br/>MCLAREN, J<br/>MFUMBA, BUHLE<br/>MFUMBA, MASELLO<br/>MILLS, MARISKA<br/>MMOLAWA, LESEDI<br/>MODISE, SEGOS<br/>MODUTLOA, MAPOSO<br/>MOKOENA, TUMI<br/>MOLELEKWA, TSHOLO<br/>MOLUSI, TK<br/>MOREBODI, THEODORE<br/>MOREMI, OLLIE<br/>MOTLHANKANE, POODITONA<br/>MPHANYA, NA<br/>MPOLE, THOPO<br/>MPOPOMA, LILA<br/>MTOMBENI, BUHLE<br/>NAKEDI, DONALD<br/>Nakisi, SA<br/>NAUDÉ, NÀDINE<br/>NEELS, WHANKIES<br/>NELL, J<br/>NEVE, T<br/>NKANYANE, M<br/>NORTMAN, W<br/>NTSHAKALA, LM<br/>NYAMAKAZI, FOFO<br/>OLIPHANT, RENE<br/>OPPERMAN, TARIEN<br/>PHAKEDI, CARLOS<br/>PHEKO, GIPSON<br/>PHILLANDER, SDM<br/>PIETERS, RUANDI<br/>PIETERSE, HESTEL<br/>PRETORIUS, DANELLE<br/>PRETORIUS, LIZETTE<br/>PRETORIUS, MARNÉ<br/>PRINS, LIZE<br/>PRINSLOO, MELISSA<br/>RAMASIMONG, CHRISTA<br/>RAMODIKE, RA<br/>RAUTENBACH, ANE<br/>REICHEL, MARTIN<br/>RIEKERT, WILLEM<br/>RÖNTGEN, JANELDA<br/>SCHOFIELD, LARNESE<br/>SENOKWANE, BOITUMELO<br/>SETSHEDI, PHENYO<br/>SLABBERT, CARLA<br/>SLABBERT, U<br/>SMIDT, JC<br/>SMIT, ANIKA<br/>SMIT, MALIZA<br/>SMIT, TLHOKS<br/>SPARKS SILVA, NATALIE<br/>STEENKAMP, ENRICH<br/>STEVENS, DG<br/>STEYN, ANGELIQUE<br/>STRAUSS, KATELYN<br/>TIRO, BINO<br/>TJABANE, MPHO<br/>TSIKANE, THABO<br/>VAN DYK, ANJA<br/>VAN HEERDEN, NICOLENE<br/>VAN HEERDEN, RONAN<br/>VAN JAARSVELD, ZELMARI<br/>VAN NIEKERK, LOUISE<br/>VAN STADEN, SUNELLE<br/>VAN TONDER, ANGIE<br/>VAN VUUREN, ANE<br/>VAN ZYL, C<br/>VAN ZYL, K<br/>VAN ZYL, LETTIE<br/>VAN ZYL, TARINE<br/>VENTER, ARMAND<br/>VILJOEN, SUNÉ<br/>VISAGIE, DENA<br/>WIEHMAN, INGE<br/>WILKINSON, MINKE<br/>WILLEMSE, ZELCKE<br/>XHOBASA, KOKETSO<br/>XHOLA, ESTHER<br/>ADAMS, CARNITA<br/>AFRIKA, MEIKIE<br/>BAEPI, OBK<br/>BAPELA, LM<br/>BLIGNAUT, SHANTELLE<br/>BOTHA, DANE<br/>BURGER, ERIK<br/>BUTHELEZI, NB<br/>BUTTRESS, N<br/>CHINSAMY, K<br/>CRIPPS, EL<br/>DLIKILILI, S<br/>DU PLESSIS, RUNE<br/>GONGOTA, M<br/>GUMBI, BUSI<br/>HENDEY, HEATHER<br/>HOMRAJ, N<br/>HUNT, MARCELLE<br/>KGASE, GOMOLEMO<br/>KHULUOE, M<br/>KRIEK, C<br/>KUNENE, LM<br/>LE ROUX, CHRISTIAAN<br/>LEBEPE, EM<br/>LEE, TB<br/>LÖTTER, CHANTÉ<br/>MACHABA, SR<br/>MAILA, M<br/>MAKOBELA, BLOCKBUSTER<br/>MALEBE, K<br/>MALEBE, KATLEGO<br/>MALULEKE, MW<br/>MARAIS, DANIE<br/>MASIU, T<br/>MATHONSI, FN<br/>MATSHOVHANA, P<br/>MATSOAI, NTHABI<br/>MOHAPI, NA<br/>MOHLALA, N<br/>MOKALAKE, TSHEPISO<br/>MOKOELE, PO<br/>MOKOENA, NTHABEY<br/>MOLEFI, RETHABILE<br/>MOLO, Y<br/>MOLOKWANE, RORISANG<br/>MOTSUKI, HP<br/>MUKOMAWABANI, M<br/>MULDER, INGRID<br/>NAUDÈ, STEAN<br/>NDADZIBAYA, LC<br/>NIEUWENHUIZEN, A<br/>NTSHAVHENI, P<br/>OLIVIER, JUSTIN<br/>PHASHA, NGAKETSE<br/>PHETOE, BAKANG<br/>RADEBE, SPHE<br/>ROBERTSON, J<br/>RUBHUSHE, MW<br/>SANYANE, MM<br/>SCHABORT, CORNEELS<br/>SEMATLA, MD<br/>SITHOLE, SS<br/>STATHAM, PD<br/>STEENKAMP, CHRISNA<br/>STEYN, C<br/>STEYN, MARZEL<br/>SWARTZ, S<br/>TSHIVHASE, MM<br/>UBISI, MAJUBA<br/>VAN REENEN, ANGELIQUE<br/>VAN TONDER, ZELMARIE<br/>VANDA, UK<br/>VILJOEN, JM
        </p>
        </div>
        <div className="image-container">
            <img src={NWU_UNESCO} alt="NWU and UNESCO" className="nwu-unesco-image" />
        </div>
        </div>
    );
}

export default ContributorsPage;
